alias ccode="cd /c/code"
alias cmderr="cd /c/cmder"

alias githide="git update-index --assume-unchanged $*"
alias gitf="git fetch $*"
alias gitfp="git fetch --prune $*"
alias gitl="git log --oneline --all --graph --decorate $*"
alias gitmf="git merge --ff-only $*"
alias gits="git status $*"
alias gitunhide="git update-index --no-assume-unchanged $*"
